<a href="https://colab.research.google.com/github/CarloR04/Challenge-Telcom_X_2/blob/main/Telcom_X_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CHALLENGE TELCOM X PARTE 2**

🎯 **Misión**

Tu nueva misión es desarrollar modelos predictivos capaces de prever qué clientes tienen mayor probabilidad de cancelar sus servicios.

La empresa quiere anticiparse al problema de la cancelación, y te corresponde a ti construir un pipeline robusto para esta etapa inicial de modelado.

## 🛠️ **Preparación de los Datos**

### **Extracción del Archivo Tratado**

Del anterior Challenge (Parte 1) se tiene dos archicos CSV que se usaran como archivos tratados:

1. **Data.csv:** Contiene todas las columnas con la signularidad de que los datos contienen strings en las respuesta binaria (SI Y NO).
2. **Data_binaria.csv:** Los datos tiene tratamiento Binario pasando los strings a (0 Y 1).

In [1]:
import pandas as pd

In [2]:
Data = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/ALURA/Challenge Telcom_X/PARTE 2/Data.csv')
Data_binaria = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/ALURA/Challenge Telcom_X/PARTE 2/Data_binaria.csv')

In [3]:
Data.head()

,ID_cliente,Permanencia,Genero_cliente,Cliente_Tercera_Edad,Pareja_Cliente,Dependientes_del_Cliente,Meses_del_Contrato,Servicio_telefonico,Multiples_lineas_telefonicas,Sus_Internet,...,Sus_Protección_al_Dispositivo,Sus_Soporte_Técnico,Sus_Tv_por_cable,sus_streaming_movies,Tipo_Contrato,Preferencia_Factura,Metodo_de_Pago,Gasto_Mensual,Gasto_Total,Cuentas_Diarias
0,0002-ORFBO,no,female,0,yes,yes,9,yes,no,dsl,...,no,yes,yes,no,one year,yes,mailed check,65.6,593.30,2.19
1,0003-MKNFE,no,male,0,no,no,9,yes,yes,dsl,...,no,no,no,yes,month-to-month,no,mailed check,59.9,542.40,2.00
2,0004-TLHLJ,yes,male,0,no,no,4,yes,no,fiber optic,...,yes,no,no,no,month-to-month,yes,electronic check,73.9,280.85,2.46
3,0011-IGKFF,yes,male,1,yes,no,13,yes,no,fiber optic,...,yes,no,yes,yes,month-to-month,yes,electronic check,98.0,1237.85,3.27
4,0013-EXCHZ,yes,female,1,yes,no,3,yes,no,fiber optic,...,no,yes,yes,no,month-to-month,yes,mailed check,83.9,267.40,2.80

In [4]:
Data_binaria.head()

,ID_cliente,Permanencia,Genero_cliente,Cliente_Tercera_Edad,Pareja_Cliente,Dependientes_del_Cliente,Meses_del_Contrato,Servicio_telefonico,Multiples_lineas_telefonicas,Sus_Internet,...,Sus_Protección_al_Dispositivo,Sus_Soporte_Técnico,Sus_Tv_por_cable,sus_streaming_movies,Tipo_Contrato,Preferencia_Factura,Metodo_de_Pago,Gasto_Mensual,Gasto_Total,Cuentas_Diarias
0,0002-ORFBO,0,female,0,1,1,9,1,0,dsl,...,0,1,1,0,one year,1,mailed check,65.6,593.30,2.19
1,0003-MKNFE,0,male,0,0,0,9,1,1,dsl,...,0,0,0,1,month-to-month,0,mailed check,59.9,542.40,2.00
2,0004-TLHLJ,1,male,0,0,0,4,1,0,fiber optic,...,1,0,0,0,month-to-month,1,electronic check,73.9,280.85,2.46
3,0011-IGKFF,1,male,1,1,0,13,1,0,fiber optic,...,1,0,1,1,month-to-month,1,electronic check,98.0,1237.85,3.27
4,0013-EXCHZ,1,female,1,1,0,3,1,0,fiber optic,...,0,1,1,0,month-to-month,1,mailed check,83.9,267.40,2.80

### **Eliminación de Columnas Irrelevantes**

Trabajaremos con el csv Binario por facilidad númerica y estadistica necesaria de los datos

In [9]:
df = Data_binaria.copy()
columns_to_drop = ['ID_cliente'] #Elimanos la columna
df = df.drop(columns=columns_to_drop)

df.head()

,Permanencia,Genero_cliente,Cliente_Tercera_Edad,Pareja_Cliente,Dependientes_del_Cliente,Meses_del_Contrato,Servicio_telefonico,Multiples_lineas_telefonicas,Sus_Internet,Sus_Seguridad_online,...,Sus_Protección_al_Dispositivo,Sus_Soporte_Técnico,Sus_Tv_por_cable,sus_streaming_movies,Tipo_Contrato,Preferencia_Factura,Metodo_de_Pago,Gasto_Mensual,Gasto_Total,Cuentas_Diarias
0,0,female,0,1,1,9,1,0,dsl,0,...,0,1,1,0,one year,1,mailed check,65.6,593.30,2.19
1,0,male,0,0,0,9,1,1,dsl,0,...,0,0,0,1,month-to-month,0,mailed check,59.9,542.40,2.00
2,1,male,0,0,0,4,1,0,fiber optic,0,...,1,0,0,0,month-to-month,1,electronic check,73.9,280.85,2.46
3,1,male,1,1,0,13,1,0,fiber optic,0,...,1,0,1,1,month-to-month,1,electronic check,98.0,1237.85,3.27
4,1,female,1,1,0,3,1,0,fiber optic,0,...,0,1,1,0,month-to-month,1,mailed check,83.9,267.40,2.80

### **Encoding**

In [10]:
df_encoding = df.copy()
df_encoding= pd.get_dummies(df, columns=['Genero_cliente', 'Sus_Internet', 'Tipo_Contrato', 'Metodo_de_Pago'])
pd.set_option('display.max_columns', None)
df_encoding.head()

,Permanencia,Cliente_Tercera_Edad,Pareja_Cliente,Dependientes_del_Cliente,Meses_del_Contrato,Servicio_telefonico,Multiples_lineas_telefonicas,Sus_Seguridad_online,Sus_Respaldo_online,Sus_Protección_al_Dispositivo,Sus_Soporte_Técnico,Sus_Tv_por_cable,sus_streaming_movies,Preferencia_Factura,Gasto_Mensual,Gasto_Total,Cuentas_Diarias,Genero_cliente_female,Genero_cliente_male,Sus_Internet_dsl,Sus_Internet_fiber optic,Sus_Internet_no,Tipo_Contrato_month-to-month,Tipo_Contrato_one year,Tipo_Contrato_two year,Metodo_de_Pago_bank transfer (automatic),Metodo_de_Pago_credit card (automatic),Metodo_de_Pago_electronic check,Metodo_de_Pago_mailed check
0,0,0,1,1,9,1,0,0,1,0,1,1,0,1,65.6,593.30,2.19,True,False,True,False,False,False,True,False,False,False,False,True
1,0,0,0,0,9,1,1,0,0,0,0,0,1,0,59.9,542.40,2.00,False,True,True,False,False,True,False,False,False,False,False,True
2,1,0,0,0,4,1,0,0,0,1,0,0,0,1,73.9,280.85,2.46,False,True,False,True,False,True,False,False,False,False,True,False
3,1,1,1,0,13,1,0,0,1,1,0,1,1,1,98.0,1237.85,3.27,False,True,False,True,False,True,False,False,False,False,True,False
4,1,1,1,0,3,1,0,0,0,0,1,1,0,1,83.9,267.40,2.80,True,False,False,True,False,True,False,False,False,False,False,True

### **Verificación de la Proporción de Cancelación (Churn)**

In [11]:
churn_proportion = df_encoding['Permanencia'].value_counts(normalize=True)
print("Proporción de clientes por estado de permanencia:")
print(churn_proportion * 100)

Proporción de clientes por estado de permanencia:
Permanencia
0             71.198569
1             25.719004
no reporta     3.082427
Name: proportion, dtype: float64

### Nueva sección